server:
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/book_ev_hotel
      database: book_ev_hotel
  mail:
    host: MAIL_HOST
    port: 0
    username: MAIL_USERNAME
    password: MAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


constants:
  emailRegex: EMAIL_CHECK_REGEX
  passwordRegex: PASSWORD_CHECK_REGEX
  accountActivationLink: ACCOUNT_ACTIVATION_LINK

jwt:
  secret: JWT_SECRET
  timeToLiveInMillis: 360000
