spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGO_URL}
      database: ${SPRING_DATA_MONGO_DATABASE_NAME}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO


constants:
  emailRegex: ${EMAIL_VALIDATION_REGEX}
  passwordRegex: ${PASSWORD_VALIDATION_REGEX}
  accountActivationLink: ${ACCOUNT_ACTIVATION_LINK}

jwt:
  secret: ${JWT_SECRET_KEY}
  timeToLiveInMillis: ${JWT_TTL}
